# Sets up CMake variables for projects who link against OpendTect
#
# Copyright (C): dGB Beheer B. V. 
#
# $Id$
#

#Set OpendTect version
set( OpendTect_VERSION_MAJOR 6 )
set( OpendTect_VERSION_MINOR 4 )
set( OpendTect_VERSION_PATCH 0 )
set( OpendTect_FULL_VERSION "6.4.3" )

set( QTDIR /Users/Shared/appman/mac/qt/qt596/5.9.6/clang_64 )
#Setup OpendTect's binary location (if not done)
if ( NOT DEFINED OD_BINARY_BASEDIR )
    if ( APPLE )
	set ( OD_BINARY_BASEDIR ${OpendTect_DIR}/../.. )
    else()
	set ( OD_BINARY_BASEDIR ${OpendTect_DIR} )
    endif()
endif()

#Include all OpendTect Utility macros
include( ${OpendTect_DIR}/CMakeModules/OD_SetupOD.cmake )

#Set the linker path to OpendTect's libraries
link_directories( ${OD_BINARY_BASEDIR}/${OD_LIB_OUTPUT_RELPATH} )

#As backup, link to release
set ( RELEASE_RELPATH "bin/${OD_PLFSUBDIR}/Release" )
if ( NOT ( OD_LIB_OUTPUT_RELPATH STREQUAL RELEASE_RELPATH ) )
    if ( EXISTS ${OD_BINARY_BASEDIR}/${RELEASE_RELPATH} )
	link_directories( ${OD_BINARY_BASEDIR}/${RELEASE_RELPATH} )
    endif()
endif()
unset( RELEASE_RELPATH )

#List of all modules
set( OD_CORE_MODULE_NAMES_od Basic;Algo;General;Strat;Network;Batch;Geometry;EarthModel;Well;MMProc;Seis;NLA;AttributeEngine;Velocity;VolumeProcessing;PreStackProcessing;Attributes;EMAttrib;MPEEngine;WellAttrib;uiBase;uiTools;uiCmdDriver;uiFlatView;uiIo;uiSysAdm;uiNLA;uiSeis;uiStrat;uiEarthModel;uiWell;uiVelocity;uiPreStackProcessing;uiAttributes;uiVolumeProcessing;uiEMAttrib;uiMPE;uiViewer2D;uiWellAttrib;visBase;visSurvey;uiOSG;uiVis;uiODMain;AllNonUi )

#Includes of all modules
set( OD_Basic_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/Basic ${OpendTect_DIR}/include/Basic )
set( OD_Algo_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/Algo ${OpendTect_DIR}/include/Algo )
set( OD_General_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/General ${OpendTect_DIR}/include/General )
set( OD_Strat_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/Strat ${OpendTect_DIR}/include/Strat )
set( OD_Network_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/Network ${OpendTect_DIR}/include/Network )
set( OD_Batch_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/Batch ${OpendTect_DIR}/include/Batch )
set( OD_Geometry_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/Geometry ${OpendTect_DIR}/include/Geometry )
set( OD_EarthModel_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/EarthModel ${OpendTect_DIR}/include/EarthModel ${OpendTect_DIR}/spec/EarthModel )
set( OD_Well_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/Well ${OpendTect_DIR}/include/Well )
set( OD_MMProc_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/MMProc ${OpendTect_DIR}/include/MMProc )
set( OD_Seis_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/Seis ${OpendTect_DIR}/include/Seis )
set( OD_NLA_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/NLA ${OpendTect_DIR}/include/NLA )
set( OD_AttributeEngine_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/AttributeEngine ${OpendTect_DIR}/include/AttributeEngine )
set( OD_Velocity_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/Velocity ${OpendTect_DIR}/include/Velocity )
set( OD_VolumeProcessing_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/VolumeProcessing ${OpendTect_DIR}/include/VolumeProcessing )
set( OD_PreStackProcessing_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/PreStackProcessing ${OpendTect_DIR}/include/PreStackProcessing )
set( OD_Attributes_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/Attributes ${OpendTect_DIR}/include/Attributes )
set( OD_EMAttrib_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/EMAttrib ${OpendTect_DIR}/include/EMAttrib ${OpendTect_DIR}/spec/EMAttrib )
set( OD_MPEEngine_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/MPEEngine ${OpendTect_DIR}/include/MPEEngine )
set( OD_WellAttrib_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/WellAttrib ${OpendTect_DIR}/include/WellAttrib )
set( OD_uiBase_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiBase ${OpendTect_DIR}/include/uiBase )
set( OD_uiTools_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiTools ${OpendTect_DIR}/include/uiTools )
set( OD_uiCmdDriver_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiCmdDriver ${OpendTect_DIR}/include/uiCmdDriver )
set( OD_uiFlatView_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiFlatView ${OpendTect_DIR}/include/uiFlatView )
set( OD_uiIo_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiIo ${OpendTect_DIR}/include/uiIo )
set( OD_uiSysAdm_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiSysAdm ${OpendTect_DIR}/include/uiSysAdm )
set( OD_uiNLA_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiNLA ${OpendTect_DIR}/include/uiNLA )
set( OD_uiSeis_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiSeis ${OpendTect_DIR}/include/uiSeis )
set( OD_uiStrat_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiStrat ${OpendTect_DIR}/include/uiStrat )
set( OD_uiEarthModel_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiEarthModel ${OpendTect_DIR}/include/uiEarthModel )
set( OD_uiWell_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiWell ${OpendTect_DIR}/include/uiWell )
set( OD_uiVelocity_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiVelocity ${OpendTect_DIR}/include/uiVelocity )
set( OD_uiPreStackProcessing_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiPreStackProcessing ${OpendTect_DIR}/include/uiPreStackProcessing )
set( OD_uiAttributes_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiAttributes ${OpendTect_DIR}/include/uiAttributes )
set( OD_uiVolumeProcessing_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiVolumeProcessing ${OpendTect_DIR}/include/uiVolumeProcessing )
set( OD_uiEMAttrib_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiEMAttrib ${OpendTect_DIR}/include/uiEMAttrib )
set( OD_uiMPE_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiMPE ${OpendTect_DIR}/include/uiMPE )
set( OD_uiViewer2D_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiViewer2D ${OpendTect_DIR}/include/uiViewer2D )
set( OD_uiWellAttrib_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiWellAttrib ${OpendTect_DIR}/include/uiWellAttrib )
set( OD_visBase_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/visBase ${OpendTect_DIR}/include/visBase ${OpendTect_DIR}/spec/visBase )
set( OD_visSurvey_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/visSurvey ${OpendTect_DIR}/include/visSurvey )
set( OD_uiOSG_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiOSG ${OpendTect_DIR}/include/uiOSG )
set( OD_uiVis_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiVis ${OpendTect_DIR}/include/uiVis )
set( OD_uiODMain_INCLUDEPATH  ${OpendTect_DIR}_releasebuild/include/uiODMain ${OpendTect_DIR}/include/uiODMain )
set( OD_CEEMDAttrib_INCLUDEPATH  ${OpendTect_DIR}/plugins/CEEMDAttrib ${OpendTect_DIR}_releasebuild/plugins/CEEMDAttrib )
set( OD_CRS_INCLUDEPATH  ${OpendTect_DIR}/plugins/CRS ${OpendTect_DIR}_releasebuild/plugins/CRS )
set( OD_ExpAttribs_INCLUDEPATH  ${OpendTect_DIR}/plugins/ExpAttribs ${OpendTect_DIR}_releasebuild/plugins/ExpAttribs )
set( OD_GLCM_INCLUDEPATH  ${OpendTect_DIR}/plugins/GLCM ${OpendTect_DIR}_releasebuild/plugins/GLCM )
set( OD_GMT_INCLUDEPATH  ${OpendTect_DIR}/plugins/GMT ${OpendTect_DIR}_releasebuild/plugins/GMT )
set( OD_Hello_INCLUDEPATH  ${OpendTect_DIR}/plugins/Hello ${OpendTect_DIR}_releasebuild/plugins/Hello )
set( OD_HorizonAttrib_INCLUDEPATH  ${OpendTect_DIR}/plugins/HorizonAttrib ${OpendTect_DIR}_releasebuild/plugins/HorizonAttrib )
set( OD_Madagascar_INCLUDEPATH  ${OpendTect_DIR}/plugins/Madagascar ${OpendTect_DIR}_releasebuild/plugins/Madagascar )
set( OD_MadagascarAttribs_INCLUDEPATH  ${OpendTect_DIR}/plugins/MadagascarAttribs ${OpendTect_DIR}_releasebuild/plugins/MadagascarAttribs )
set( OD_Tut_INCLUDEPATH  ${OpendTect_DIR}/plugins/Tut ${OpendTect_DIR}_releasebuild/plugins/Tut )
set( OD_VoxelConnectivityFilter_INCLUDEPATH  ${OpendTect_DIR}/plugins/VoxelConnectivityFilter ${OpendTect_DIR}_releasebuild/plugins/VoxelConnectivityFilter )
set( OD_uiCEEMDAttrib_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiCEEMDAttrib ${OpendTect_DIR}_releasebuild/plugins/uiCEEMDAttrib )
set( OD_uiCRS_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiCRS ${OpendTect_DIR}_releasebuild/plugins/uiCRS )
set( OD_uiDPSDemo_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiDPSDemo ${OpendTect_DIR}_releasebuild/plugins/uiDPSDemo )
set( OD_uiExpAttribs_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiExpAttribs ${OpendTect_DIR}_releasebuild/plugins/uiExpAttribs )
set( OD_uiGLCM_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiGLCM ${OpendTect_DIR}_releasebuild/plugins/uiGLCM )
set( OD_uiGMT_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiGMT ${OpendTect_DIR}_releasebuild/plugins/uiGMT )
set( OD_uiGoogleIO_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiGoogleIO ${OpendTect_DIR}_releasebuild/plugins/uiGoogleIO )
set( OD_uiSEGY_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiSEGY ${OpendTect_DIR}_releasebuild/plugins/uiSEGY )
set( OD_uiHello_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiHello ${OpendTect_DIR}_releasebuild/plugins/uiHello )
set( OD_uiHorizonAttrib_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiHorizonAttrib ${OpendTect_DIR}_releasebuild/plugins/uiHorizonAttrib )
set( OD_uiImpGPR_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiImpGPR ${OpendTect_DIR}_releasebuild/plugins/uiImpGPR )
set( OD_uiMadagascar_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiMadagascar ${OpendTect_DIR}_releasebuild/plugins/uiMadagascar )
set( OD_uiMadagascarAttribs_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiMadagascarAttribs ${OpendTect_DIR}_releasebuild/plugins/uiMadagascarAttribs )
set( OD_uiPresentationMaker_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiPresentationMaker ${OpendTect_DIR}_releasebuild/plugins/uiPresentationMaker )
set( OD_uiQtApp_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiQtApp ${OpendTect_DIR}_releasebuild/plugins/uiQtApp )
set( OD_uiTut_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiTut ${OpendTect_DIR}_releasebuild/plugins/uiTut )
set( OD_uiTutMadagascar_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiTutMadagascar ${OpendTect_DIR}_releasebuild/plugins/uiTutMadagascar )
set( OD_uiVoxelConnectivityFilter_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiVoxelConnectivityFilter ${OpendTect_DIR}_releasebuild/plugins/uiVoxelConnectivityFilter )
set( OD_uiPreStackViewer_INCLUDEPATH  ${OpendTect_DIR}/plugins/uiPreStackViewer ${OpendTect_DIR}_releasebuild/plugins/uiPreStackViewer )
set( OD_CmdDriver_INCLUDEPATH  ${OpendTect_DIR}/plugins/CmdDriver ${OpendTect_DIR}_releasebuild/plugins/CmdDriver )


#Dependencies of all modules
set( OD_Algo_DEPS Basic )
set( OD_General_DEPS Algo )
set( OD_Strat_DEPS General )
set( OD_Network_DEPS General )
set( OD_Batch_DEPS Network )
set( OD_Geometry_DEPS General )
set( OD_EarthModel_DEPS Geometry )
set( OD_Well_DEPS General )
set( OD_MMProc_DEPS Network )
set( OD_Seis_DEPS Geometry;MMProc )
set( OD_NLA_DEPS General )
set( OD_AttributeEngine_DEPS NLA;Seis )
set( OD_Velocity_DEPS AttributeEngine;EarthModel )
set( OD_VolumeProcessing_DEPS Velocity;Well )
set( OD_PreStackProcessing_DEPS Velocity )
set( OD_Attributes_DEPS AttributeEngine;PreStackProcessing )
set( OD_EMAttrib_DEPS EarthModel;AttributeEngine )
set( OD_MPEEngine_DEPS EarthModel;AttributeEngine )
set( OD_WellAttrib_DEPS Well;Attributes;Strat )
set( OD_uiBase_DEPS Network )
set( OD_uiTools_DEPS uiBase;MMProc )
set( OD_uiCmdDriver_DEPS uiTools )
set( OD_uiFlatView_DEPS uiTools )
set( OD_uiIo_DEPS uiTools;uiFlatView;Geometry )
set( OD_uiSysAdm_DEPS uiIo )
set( OD_uiNLA_DEPS uiIo;NLA;Well;Seis )
set( OD_uiSeis_DEPS uiIo;Seis;Velocity )
set( OD_uiStrat_DEPS uiIo;Strat )
set( OD_uiEarthModel_DEPS uiStrat;EarthModel )
set( OD_uiWell_DEPS uiStrat;Well )
set( OD_uiVelocity_DEPS uiSeis;Velocity )
set( OD_uiPreStackProcessing_DEPS uiSeis;PreStackProcessing )
set( OD_uiAttributes_DEPS uiPreStackProcessing;Attributes )
set( OD_uiVolumeProcessing_DEPS uiVelocity;uiWell;uiAttributes;uiEarthModel;VolumeProcessing )
set( OD_uiEMAttrib_DEPS uiAttributes;uiEarthModel;EMAttrib )
set( OD_uiMPE_DEPS uiAttributes;uiFlatView;MPEEngine )
set( OD_uiViewer2D_DEPS uiMPE )
set( OD_uiWellAttrib_DEPS uiWell;uiAttributes;WellAttrib )
set( OD_visBase_DEPS Geometry )
set( OD_visSurvey_DEPS visBase;EarthModel;MPEEngine;Well;PreStackProcessing )
set( OD_uiOSG_DEPS visSurvey;uiTools )
set( OD_uiVis_DEPS uiOSG;uiMPE )
set( OD_uiODMain_DEPS uiVis;uiVolumeProcessing;uiNLA;uiWellAttrib;uiEMAttrib;uiViewer2D )
set( OD_CEEMDAttrib_DEPS AttributeEngine )
set( OD_CRS_DEPS Basic )
set( OD_ExpAttribs_DEPS AttributeEngine )
set( OD_GLCM_DEPS AttributeEngine )
set( OD_GMT_DEPS EarthModel;Seis;Well )
set( OD_Hello_DEPS Basic )
set( OD_HorizonAttrib_DEPS Basic;Algo;AttributeEngine;PreStackProcessing;Attributes;EarthModel;MPEEngine )
set( OD_Madagascar_DEPS AttributeEngine )
set( OD_MadagascarAttribs_DEPS Attributes )
set( OD_Tut_DEPS AttributeEngine;EarthModel;VolumeProcessing;Well )
set( OD_VoxelConnectivityFilter_DEPS VolumeProcessing )
set( OD_uiCEEMDAttrib_DEPS uiAttributes;CEEMDAttrib )
set( OD_uiCRS_DEPS uiODMain;CRS )
set( OD_uiDPSDemo_DEPS uiODMain )
set( OD_uiExpAttribs_DEPS ExpAttribs;uiODMain )
set( OD_uiGLCM_DEPS uiODMain;GLCM )
set( OD_uiGMT_DEPS uiODMain;GMT )
set( OD_uiGoogleIO_DEPS uiODMain )
set( OD_uiSEGY_DEPS uiODMain )
set( OD_uiHello_DEPS uiODMain )
set( OD_uiHorizonAttrib_DEPS uiODMain;HorizonAttrib )
set( OD_uiImpGPR_DEPS uiODMain )
set( OD_uiMadagascar_DEPS uiODMain;Madagascar )
set( OD_uiMadagascarAttribs_DEPS uiAttributes;MadagascarAttribs )
set( OD_uiPresentationMaker_DEPS uiODMain )
set( OD_uiQtApp_DEPS uiODMain )
set( OD_uiTut_DEPS uiODMain;Tut )
set( OD_uiTutMadagascar_DEPS Seis;uiFlatView;uiODMain;Madagascar )
set( OD_uiVoxelConnectivityFilter_DEPS uiODMain;VoxelConnectivityFilter )
set( OD_uiPreStackViewer_DEPS uiODMain )
set( OD_CmdDriver_DEPS uiCmdDriver;uiODMain )


set( OD_THIRD_PARTY_LIBS QtCore;QtNetwork;QtWidgets;QtPrintSupport;libosg.158.dylib;libosgDB.158.dylib;libosgGA.158.dylib;libosgUtil.158.dylib;libosgQt5.145.dylib;libosgManipulator.158.dylib;libosgWidget.158.dylib;libosgViewer.158.dylib;libosgVolume.158.dylib;libOpenThreads.21.dylib;libosgText.158.dylib;libosgSim.158.dylib;QtOpenGL;QtGui;libproj.14.dylib )
